version: '3.8'
services:
  evfhq-assigner:
    build: .
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: host.docker.internal 
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_PORT: your_db_port
      RABBITMQ_HOST: host.docker.internal  
      RABBITMQ_PORT: your_rabbitmq_port

volumes:
  postgres-data:
  rabbitmq-data:

networks:
  default:
